### ISSUE TITLE
09-17 23:01:34 +0800 ERROR [NioProcessor-2] - ERRORjava.sql.SQLDataException: Unsupported conversion from TIMESTAMP to java.lang.Long

### ISSUE THREAD

**Issue by jcc563768606** [mrzhqiang/ms079#13]
能启动但是进客户端输入账号密码会提示账号不存在，服务端就是报这个error

**Comment by jcc563768606** [comment]
主要是我也不知道哪一行报错的，能把错误堆栈打出来么

**Comment by jcc563768606** [comment]
mysql版本是5.7.35

**Comment by jcc563768606** [comment]
rs.getLong("tempban")这行

**Comment by jcc563768606** [comment]
我换成rs.getTimesTamp("tempban").getTime()

**Comment by jcc563768606** [comment]
遇见新的问题了
Error saving MACscom.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction

**Comment by mrzhqiang** [comment]
你这个是新版本还是你之前fork的版本？

**Comment by jcc563768606** [comment]
client.MapleClient#updateMacs(java.lang.String)
这个地方锁等待了

**Comment by jcc563768606** [comment]
> 你这个是新版本还是你之前fork的版本？

新版本的

**Comment by mrzhqiang** [comment]
> > 你这个是新版本还是你之前fork的版本？
> 
> 新版本的

新版本还没测试好，换回去吧

**Comment by mrzhqiang** [comment]
新版本还没完全重构完毕

**Comment by jcc563768606** [comment]
哎，老版本各种bug，我就等你重构了😅敲碗期待

**Comment by jcc563768606** [comment]
老哥，啥时候bug改完了，你和我说一声，我给你测

**Comment by duwei54** [comment]
我也遇到这个问题了

**Comment by mrzhqiang** [comment]
事务锁表之后，再进入事务会等待。解决方案是：将原来旧的 jdbc 连接，改为 ebean 的查询语句，使用 Q*** Bean 查询，或 DB.** 方法查询，都可以，或者也可以用原生查询，但记得提交事务。

**Comment by mrzhqiang** [comment]
我在 feature 中已修复此问题，但遇到了基于 jdbc 的老问题，选择角色无法进入游戏，接下来的重点任务是排查 jdbc 这一类老问题，重构为 ebean 查询（优化的查询语句，比手写 jdbc 更快）。

**Comment by mrzhqiang** [comment]
develop 分支已经从 JDBC 转为 Ebean，类型转换异常已不再是问题所在。
