### ISSUE TITLE
登录已有账号的时候 报错，Unsupported conversion from TIMESTAMP to java.lang.Long 但不知道是哪个字段

### ISSUE THREAD

**Issue by yihaoshi** [mrzhqiang/ms079#16]
登录已有账号的时候 报错，Unsupported conversion from TIMESTAMP to java.lang.Long 但不知道是哪个字段

![image](https://user-images.githubusercontent.com/26559319/157417387-1eabff36-5095-4ee2-97c5-d416b02c6809.png)

**Comment by yihaoshi** [comment]
已解决，MapleClient.java 更改以下内容即可
![image](https://user-images.githubusercontent.com/26559319/157806501-461a1611-4514-4a42-b4ef-084d15bdc33b.png)

**Comment by h93910** [comment]
> 已解决，MapleClient.java 更改以下内容即可 ![image](https://user-images.githubusercontent.com/26559319/157806501-461a1611-4514-4a42-b4ef-084d15bdc33b.png)

謝謝哥們
