### ISSUE TITLE
[BUG]编译时报错

### ISSUE THREAD

**Issue by Rolsieya** [mrzhqiang/ms079#17]
**Describe the bug**

![1649298585(1)](https://user-images.githubusercontent.com/30484799/162108508-cb399f36-d2a0-4e9d-a81b-110b380e4f4b.jpg)
在项目根节点调用mvn clean compile时编译报错

**(Optional) About information**

(【可选的】相关信息)

- `OS version`: Windows 10 10.0
- `Branchs Tags or Commit Revision`:
  - main
  - revision edcbd94
- `Your customize`: 大佬能教教linux搭环境吗

**Comment by mrzhqiang** [comment]
相关信息过少，无法判断编译的问题出在哪里，请提供编译的 Maven 版本 JDK 版本，以及对应的 Maven 设置项是否从 java1.6 指定为 java8

**Comment by EnixCoda** [comment]
遇到同样的问题。不太熟悉 Java 开发，这里提供一下操作过程

1. 用 IDEA 打开项目
2. 在 IDEA 项目设置中设置 JDK 版本为 azul1.8
3. 在 pom.xml 被报错——项目经由版本 55 的 JDK 编译，当前版本为 52。查了查发现 52 是 java 1.8，55 是 java 11。
4. 在 IDEA 项目设置中设置 JDK 版本为 11
5. pom.xml 的报错消失，IDEA 开始报主楼截图中的类型问题

---

再用 openjdk 试了试，这次的情况不一样了

0. 手动安装 openjdk 1.8
1. 用 IDEA 打开项目
2. 在 IDEA 项目设置中设置 JDK 版本为 openjdk 1.8
3. 运行 Maven `clean`，成功
4. 运行 Maven `package`，报错如下
    `Could not find artifact com.github.mrzhqiang.helper:helper:pom:2021.1.3 in central (https://repo.maven.apache.org/maven2)`
