### ISSUE TITLE
java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.

### ISSUE THREAD

**Issue by Shawn-Wu** [mrzhqiang/ms079#2]
........
[自动存档] 已经将 0 个玩家保存到数据中.
服务端启用在线时间记录.1分钟自动记录一次
SpeedRunner错误:java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.

经验倍率:2  物品倍率：2  金币倍率2

当前开放职业:  冒险家 = true 骑士团 = false 战神 = false

服务端启动完毕 可以进入游戏了:::
java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.
java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY.

**Comment by mrzhqiang** [comment]
这个应该跟你的 MySQL 数据库版本有关，或者在你的 my.ini 设置中，有改动。

我使用 5.7.30 版本的 MySQL 数据库，没有遇到此类问题。

**Comment by Shawn-Wu** [comment]
> 这个应该跟你的 MySQL 数据库版本有关，或者在你的 my.ini 设置中，有改动。
> 
> 我使用 5.7.30 版本的 MySQL 数据库，没有遇到此类问题。
我换了mysql 5.7.35 又报别的错
ERRORjava.sql.SQLDataException: Unsupported conversion from TIMESTAMP to java.lang.Long

**Comment by mrzhqiang** [comment]
问题挺多的，原版本的MySQL版本是4.3+，高版本应该没有兼容。



---Original---
From: "XIN ***@***.***&gt;
Date: Sun, Aug 15, 2021 18:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mrzhqiang/ms079] java.sql.SQLException: Operation not allowed for a result set of type ResultSet.TYPE_FORWARD_ONLY. (#2)




  
这个应该跟你的 MySQL 数据库版本有关，或者在你的 my.ini 设置中，有改动。
 
我使用 5.7.30 版本的 MySQL 数据库，没有遇到此类问题。
 我换了mysql 5.7.35 又报别的错
 ERRORjava.sql.SQLDataException: Unsupported conversion from TIMESTAMP to java.lang.Long

**Comment by mrzhqiang** [comment]
![](https://user-images.githubusercontent.com/18276822/130330966-c0de8860-ee08-4dcd-9623-3ce11c6d5bef.png)
修复此问题的关键。

**Comment by mrzhqiang** [comment]
参考 #8 的修复。
