### ISSUE TITLE
你好 可以留个联系方式吗 有关于客户端和服务端怎么调试的问题想咨询下

### ISSUE THREAD

**Issue by vaz-sso** [mrzhqiang/ms079#20]
**Describe the bug**

(简洁清楚地描述 BUG 是什么)
- 发现异常的【堆栈日志】 
- 出现问题的【屏幕截图】
- 可以复现的【详细步骤】
- 你所猜测的【关键因素】 
- 其他相关的【文字描述】

**Expected behavior**

(简洁清楚地描述期望的行为)

1. 正常情况下，应该/不应该 发生的行为
2. 特殊情况下，应该/不应该 发生的行为

**(Optional) About information**

(【可选的】相关信息)

- `OS version`: Windows 10 10.0
- `Java`: Oracle JDK 1.8.0_301
- `DB`: MySQL 5.7.30-log
- `Branchs Tags or Commit Revision`:
  - main
  - develop
  - release-[x.x]
  - tag 1.0
  - revision 1398406e
- `Project version`: 1.0-SNAPSHOT
- `Your customize`: other information

**Comment by mrzhqiang** [comment]
看github主页有联系方式
