### ISSUE TITLE
通过Maven 插件使用 mvn clean package 命令进行打包时候报这个错误

### ISSUE THREAD

**Issue by a614349007** [mrzhqiang/ms079#24]
![image](https://github.com/mrzhqiang/ms079/assets/117435488/560fb4a0-cee3-493d-9d38-0d5f93148542)
通过Maven 插件使用 mvn clean package 命令进行打包时候报这个错误，麻烦能解答下是什么问题么

**Comment by mrzhqiang** [comment]
老生常谈，单元测试中的编码问题，你可以在运行Maven命令时，跳过单元测试

**Comment by a614349007** [comment]
谢谢，按您说的确实打包成功了，然后现在打开客户端它报这个错误，麻烦您再解答下是什么问题。。还有我下载您发的那个客户端但是安装完成后显示是v199的..
![image](https://github.com/mrzhqiang/ms079/assets/117435488/82fa5fa8-0dab-475a-b0ec-8449184ad460)
![image](https://github.com/mrzhqiang/ms079/assets/117435488/afdff130-c287-4da9-a654-25c3d78f6760)

**Comment by mrzhqiang** [comment]
v199 只是盛大弹窗广告的当前版本，和你安装的客户端版本无关。
另外客户端报错，请参考 README 里面的步骤，替换相关文件。

**Comment by a614349007** [comment]
不好意思，再打扰你一下，这个客户端账号用的是哪里是账号，我输入几个都不存在。。。

**Comment by a614349007** [comment]
是在数据库添加的accounts表添加么，这密码的加密方式是什么。。

**Comment by mrzhqiang** [comment]
时间比较久了，你试试：1 或者 1234 或者 123456 之类的
