### ISSUE TITLE
[BUG]运行客户端游戏在登录界面锁表了

### ISSUE THREAD

**Issue by Qadatank** [mrzhqiang/ms079#25]
服务端生成成功，也执行成功，运行着；
但是在运行客户端之后，在登录界面输入账号密码，提示了Lock wait timeout exceeded; try restarting transaction
登录验证的sql语句 在Mysql系统表中都被锁了，点击人物 也提示连接服务器失败，麻烦看到了 解答下

**Comment by Qadatank** [comment]
优化了sql自动提交事务之后，可以登录到选择人物界面，但是选择人物，提示与服务器断开连接，登不进去

**Comment by mrzhqiang** [comment]
你找第一次提交的版本吧，最新版本和develop分支的版本没做完，所以问题很多……
