### ISSUE TITLE
代码是最新的吗，我运行直接显示NPE，GUI的icon没有，我直接注释掉了

### ISSUE THREAD

**Issue by jcc563768606** [mrzhqiang/ms079#6]
![image](https://user-images.githubusercontent.com/11483516/130260692-d82295a3-20cf-4898-8038-d768a6d2eea9.png)
，你写的这个控制台有了，
![image](https://user-images.githubusercontent.com/11483516/130260809-da786edf-0ab5-4f67-aec6-1a265db24cbe.png)
但是还是报了后续的错误

**Comment by jcc563768606** [comment]
看起来是少了old-files里的这个
![image](https://user-images.githubusercontent.com/11483516/130261066-bfdc8967-497e-4b35-b56a-fb3fecf5f904.png)

**Comment by mrzhqiang** [comment]
已修复此类问题
